import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Dry Cat Food",
    description: "High-quality dry food for adult cats with balanced nutrition and great taste.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?q=80&w=600&auto=format&fit=crop",
    category: "food",
    pet: "cat",
    rating: 4.5,
    reviewCount: 128,
    isNew: false,
    featured: true,
    stock: 50,
    tags: ["food", "nutrition", "adult cats"],
  },
  {
    id: "2",
    name: "Interactive Cat Toy",
    description: "Engaging toy that stimulates your cat's hunting instincts and provides hours of entertainment.",
    price: 12.99,
    originalPrice: 16.99,
    image: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?q=80&w=600&auto=format&fit=crop",
    category: "toys",
    pet: "cat",
    rating: 4.8,
    reviewCount: 95,
    isNew: true,
    discount: 20,
    featured: true,
    stock: 35,
    tags: ["toys", "interactive", "entertainment"],
  },
  {
    id: "3",
    name: "Premium Dog Kibble",
    description: "Complete and balanced nutrition for adult dogs of all breeds.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1585846888147-3fe14c130048?q=80&w=600&auto=format&fit=crop",
    category: "food",
    pet: "dog",
    rating: 4.7,
    reviewCount: 203,
    featured: true,
    stock: 45,
    tags: ["food", "nutrition", "adult dogs"],
  },
  {
    id: "4",
    name: "Durable Dog Chew Toy",
    description: "Long-lasting chew toy designed for aggressive chewers.",
    price: 18.99,
    originalPrice: 22.99,
    image: "https://images.unsplash.com/photo-1575425186775-b8de9a427e67?q=80&w=600&auto=format&fit=crop",
    category: "toys",
    pet: "dog",
    rating: 4.6,
    reviewCount: 167,
    discount: 15,
    featured: true,
    stock: 30,
    tags: ["toys", "durable", "chew"],
  },
  {
    id: "5",
    name: "Cat Immune Support Supplements",
    description: "Daily supplements to boost your cat's immune system and overall health.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?q=80&w=600&auto=format&fit=crop",
    category: "supplements",
    pet: "cat",
    rating: 4.3,
    reviewCount: 78,
    isNew: true,
    featured: true,
    stock: 25,
    tags: ["supplements", "health", "immune system"],
  },
  {
    id: "6",
    name: "Dog Joint Health Supplements",
    description: "Support your dog's joint health and mobility with these tasty chewable tablets.",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1582798358481-d199fb7347bb?q=80&w=600&auto=format&fit=crop",
    category: "supplements",
    pet: "dog",
    rating: 4.5,
    reviewCount: 112,
    featured: true,
    stock: 40,
    tags: ["supplements", "joint health", "mobility"],
  },
  {
    id: "7",
    name: "Catnip Mice Toys (3-Pack)",
    description: "Set of three catnip-filled mice toys that cats love to chase and pounce on.",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=600&auto=format&fit=crop",
    category: "toys",
    pet: "cat",
    rating: 4.2,
    reviewCount: 63,
    featured: false,
    stock: 55,
    tags: ["toys", "catnip", "play"],
  },
  {
    id: "8",
    name: "Dog Tennis Ball Launcher",
    description: "Interactive toy that launches tennis balls for your dog to fetch.",
    price: 24.99,
    originalPrice: 29.99,
    image: "https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?q=80&w=600&auto=format&fit=crop",
    category: "toys",
    pet: "dog",
    rating: 4.4,
    reviewCount: 89,
    discount: 15,
    featured: true,
    stock: 20,
    tags: ["toys", "interactive", "fetch"],
  },
  {
    id: "9",
    name: "Wet Cat Food Variety Pack",
    description: "Assorted flavors of premium wet food that cats love.",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1600456899121-68eda5705257?q=80&w=600&auto=format&fit=crop",
    category: "food",
    pet: "cat",
    rating: 4.6,
    reviewCount: 142,
    featured: false,
    stock: 60,
    tags: ["food", "wet food", "variety"],
  },
  {
    id: "10",
    name: "Dog Dental Chews",
    description: "Tasty treats that help clean your dog's teeth and freshen breath.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?q=80&w=600&auto=format&fit=crop",
    category: "food",
    pet: "dog",
    rating: 4.3,
    reviewCount: 76,
    featured: false,
    stock: 45,
    tags: ["dental care", "treats", "oral health"],
  },
  {
    id: "11",
    name: "Cat Scratching Post",
    description: "Durable sisal scratching post with a plush top perch for lounging.",
    price: 39.99,
    originalPrice: 49.99,
    image: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?q=80&w=600&auto=format&fit=crop",
    category: "toys",
    pet: "cat",
    rating: 4.7,
    reviewCount: 118,
    discount: 20,
    featured: true,
    stock: 15,
    tags: ["furniture", "scratching", "activity"],
  },
  {
    id: "12",
    name: "Dog Anxiety Calming Vest",
    description: "Gentle pressure vest that helps reduce anxiety during thunderstorms or travel.",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?q=80&w=600&auto=format&fit=crop",
    category: "supplements",
    pet: "dog",
    rating: 4.1,
    reviewCount: 52,
    isNew: true,
    featured: false,
    stock: 25,
    tags: ["anxiety", "calming", "travel"],
  },
  {
    id: "13",
    name: "Cat Hairball Control Treats",
    description: "Tasty treats that help reduce hairballs and support digestive health.",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1623387641168-d9803ddd3f35?q=80&w=600&auto=format&fit=crop",
    category: "supplements",
    pet: "cat",
    rating: 4.4,
    reviewCount: 87,
    featured: false,
    stock: 40,
    tags: ["hairball", "treats", "digestive health"],
  },
  {
    id: "14",
    name: "Dog Training Treats Pouch",
    description: "Convenient pouch for carrying training treats during walks and training sessions.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?q=80&w=600&auto=format&fit=crop",
    category: "toys",
    pet: "dog",
    rating: 4.2,
    reviewCount: 64,
    featured: false,
    stock: 30,
    tags: ["training", "accessories", "treats"],
  },
  {
    id: "15",
    name: "Cat Water Fountain",
    description: "Flowing water fountain that encourages cats to drink more water.",
    price: 29.99,
    originalPrice: 34.99,
    image: "https://images.unsplash.com/photo-1516750105099-4b8a83e217ee?q=80&w=600&auto=format&fit=crop",
    category: "food",
    pet: "cat",
    rating: 4.5,
    reviewCount: 103,
    discount: 15,
    featured: true,
    stock: 20,
    tags: ["water", "hydration", "fountain"],
  },
  {
    id: "16",
    name: "Dog Probiotic Supplements",
    description: "Daily probiotics to support your dog's digestive and immune health.",
    price: 27.99,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?q=80&w=600&auto=format&fit=crop",
    category: "supplements",
    pet: "dog",
    rating: 4.6,
    reviewCount: 91,
    isNew: true,
    featured: false,
    stock: 35,
    tags: ["supplements", "digestive health", "probiotics"],
  },
]
